export default {
	API_BASE_URL: process.env.REACT_APP_API_BASE_URL,
	MAPS_API_KEY: process.env.REACT_APP_MAPS_API_KEY,
	AVIATIONSTACK_API_KEY: process.env.REACT_APP_AVIATIONSTACK_API_KEY,
	AVIATIONSTACK_BASE_URL: process.env.REACT_APP_AVIATIONSTACK_BASE_URL,
	TOKEN_KEY: process.env.REACT_APP_TOKEN_KEY
}
